# --- !Ups

ALTER TABLE licenciamento.tipo_documento ADD COLUMN id_usuario_licenciamento INTEGER;
ALTER TABLE licenciamento.tipo_documento ADD COLUMN data_cadastro timestamp without time zone;
ALTER TABLE licenciamento.tipo_documento ADD COLUMN ativo BOOLEAN DEFAULT 'true';

COMMENT ON COLUMN licenciamento.tipo_documento.id_usuario_licenciamento IS 'Identificador único da entidade usuario_licenciamento.';
COMMENT ON COLUMN licenciamento.tipo_documento.data_cadastro IS 'Data de cadastro do documento.';
COMMENT ON COLUMN licenciamento.tipo_documento.ativo IS 'Determina se um item documento está ativo ou inativo';

DELETE FROM licenciamento.tipo_documento a
    where exists (select 1 from licenciamento.tipo_documento b
        WHERE a.nome=b.nome
        AND a.id <> b.id
        AND (select count(*) from licenciamento.documento where id_tipo_documento = a.id) = 0
        AND (select count(*) from licenciamento.rel_tipo_licenca_grupo_documento where id_tipo_documento = a.id) = 0
        AND (select count(*) from licenciamento.tipo_documento_tipo_licenca where id_tipo_documento = a.id) = 0);

ALTER TABLE licenciamento.tipo_documento ADD CONSTRAINT uq_nome_tipo_documento UNIQUE (nome);


# --- !Downs

ALTER TABLE licenciamento.tipo_licenca DROP CONSTRAINT uq_nome_tipo_documento;

INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (1, 'Documento comprobatório de representação', null, 'documento_representacao', 'documento_representacao', null, null);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (71, 'RLO - Renovação da Licença de Operação', null, 'RLO', 'RLO', 'DOC_RLO', null);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (101, 'Instrumento público ou particular de procuração se for o caso, com respectiva Cédula de Identidade (RG) e Cadastro de Pessoa Física (CPF) do procurador', null, 'procuracao', 'procuracao', null, 0);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (102, 'Cédula de Identidade (RG) e Cadastro de Pessoa Física (CPF) do interessado', null, 'identidade', 'identidade', null, 0);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (103, 'Alvará de funcionamento emitido pela Prefeitura Municipal ou Alvará de Obra emitido pela Prefeitura Municipal, declarando que o local e o tipo de empreendimento estão em conformidade com a legislação aplicável ao uso e ocupação do solo', null, 'alvara', 'alvara', null, 0);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (104, 'Anotação de Responsabilidade Técnica (ART), ou documento similar emitido pelo Conselho de Classe, dos projetos e estudos apresentados', null, 'art', 'art', null, 1);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (105, 'Projeto de Engenharia Ambiental, de acordo com o TR', null, 'tr', 'tr', null, 1);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (106, 'Alvará de funcionamento emitido pela Prefeitura Municipal ou Certidão, declarando que o local e o tipo de empreendimento estão em conformidade com a legislação aplicável ao uso e ocupação do solo', null, 'alvara_certidao', 'alvara_certidao', null, 0);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (107, 'Registro comercial, no caso de empresa individual', null, 'registro_com', 'registro_com', null, 0);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (108, 'Ato constitutivo, estatuto ou contrato social em vigor, devidamente registrado, em se tratando de sociedades comerciais, e, no caso de sociedades por ações, acompanhado de documentos de eleição de seus administradores;', null, 'ato_constitutivo', 'ato_constitutivo', null, 0);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (109, 'Comprovação de regularidade fundiária se for o caso', null, 'reg_fundiaria', 'reg_fundiaria', null, 0);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (110, 'Prova de inscrição no Cadastro Nacional de Pessoas Jurídicas (CNPJ) e prova de inscrição no Cadastro de Contribuinte Estadual (IE)Prova de isenção de contribuição estadual, se for o caso. ', null, 'cnpj', 'cnpj', null, 0);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (111, 'Planta de localização do empreendimento, com indicação do norte geográfico e os ventos predominantes, em escala adequada, indicando limites e a situação do terreno em relação aos cursos d´água, identificando o ponto de lançamento dos efluentes das águas domésticas e residuárias após tratamento, ou croqui indicando os mesmos elementos requeridos para a referida planta;', null, 'planta_localiz', 'planta_localiz', null, 1);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (112, 'Documentos técnicos como consta no TR', null, 'doc_tecnicos', 'doc_tecnicos', null, 1);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (113, 'Memorial Descritivo das obras a serem executadas devendo conter as informações como consta no TR', null, 'memorial_desc', 'memorial_desc', null, 1);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (114, 'Alvará de licença da prefeitura municipal, atualizado e autenticado, detalhando o tipo de atividade e localização do empreendimento ou atividade', null, 'alvara_licenca', 'alvara_licenca', null, 0);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (116, 'Cópia do requerimento padrão protocolado no DNPM', null, 'dnpm', 'dnpm', null, 0);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (117, 'Cópia da Outorga preventiva ou outorga de direito de uso dos recursos hídricos (captação e/ou lançamento) ou Dispensa de outorga concedidas pela Agência Nacional de Águas, quando for o caso;', null, 'outorga', 'outorga', 'COPIA_OUTORGA_ANA', 1);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (118, 'Cópia da publicação do pedido de licença Ambiental no diário oficial do estado do Pará', null, 'lic_amb_do', 'lic_amb_do', null, 0);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (119, 'Cópia da publicação do pedido de licença Ambiental em jornal local de grande circulação', null, 'lic_amb_jornal', 'lic_amb_jornal', null, 0);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (120, 'Requerente pessoa física: CPF (cópia autenticada)', null, 'cpf_req', 'cpf_req', null, 0);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (121, 'Requerente pessoa física: RG (cópia autenticada)', null, 'rg_req', 'rg_req', null, 0);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (122, 'Procuração para o representante (cópia autenticada e assinaturas reconhecidas)', null, 'procuracao_rep', 'procuracao_rep', null, 0);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (123, 'CPF do procurador (cópia autenticada)', null, 'cpf_proc', 'cpf_proc', null, 0);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (124, 'RG do procurador (cópia autenticada)', null, 'rg_proc', 'rg_proc', null, 0);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (125, 'Requerente pessoa jurídica:  Comprovante de inscrição no Cadastro Nacional de Pessoas Jurídicas (CNPJ) atualizado, com a descrição da atividade a ser licenciada (cópia autenticada)', null, 'cnpj_atv', 'cnpj_atv', null, 0);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (126, 'Requerente pessoa jurídica: Comprovante de inscrição no cadastro de contribuintes estadual, com validade ainda em vigor, incluindo a descrição da atividade a ser licenciada (cópia autenticada);', null, 'cnpj_cce', 'cnpj_cce', null, 0);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (127, 'CPF do representante legal (cópia autenticada)', null, 'cpf_rlegal', 'cpf_rlegal', null, 0);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (128, 'RG do representante legal (cópia autenticada)', null, 'rg_rlegal', 'rg_rlegal', null, 0);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (129, 'Contrato social e última alteração, no caso de empresa por cotas limitadas (LTDA), ou Ata da última assembleia, onde se definiu a diretoria, no caso de sociedade anônima (S.A) ou declaração de firma individual ou Estatuto social da empresa registrada na JUCEPA (cópia autenticada)', null, 'contrato_social', 'contrato_social', null, 0);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (130, 'Caso o requerente tenha o domínio da propriedade e este seja comprovado por titulo definitivo, apresentar certidão atualizada do cartório de registro de imóveis ou compromisso público ou particular de compra e venda;', null, 'certidao_cart', 'certidao_cart', null, 0);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (131, 'Não havendo título definitivo na área de interesse, o requerente poderá apresentar documento de posse, a qual será exigida a certidão administrativa fornecida pelo órgão competente ou escritura possessória lavrada em cartório reconhecida pelos confinantes;', null, 'posse', 'posse', null, 0);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (132, 'Alvará de funcionamento emitido pela Prefeitura Municipal onde está instalada a ERB ou Certidão, declarando que o local e o tipo de empreendimento estão em conformidade com a legislação aplicável ao uso e ocupação do solo', null, 'alvara_erb', 'alvara_erb', null, 0);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (133, 'Cédula de Identidade (RG) e Cadastro de Pessoa Física - CPF do interessado;', null, 'rg_cpf', 'rg_cpf', null, 0);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (134, 'Prova de inscrição no Cadastro Nacional de Pessoas Jurídicas (CNPJ)', null, 'insc_cnpj', 'insc_cnpj', null, 0);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (135, 'Prova de inscrição no Cadastro de Contribuinte Estadual (IE)', null, 'ie', 'ie', null, 0);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (136, 'Registro de imóveis ou do contrato de locação relativo à propriedade onde será exercida a atividade a ser licenciada (cópia)', null, 'r_imovel', 'r_imovel', null, 0);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (137, 'Aprovação do Estudo de Impacto de Vizinhança – EIV pelo município', null, 'eiv', 'eiv', null, 1);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (138, 'Anotação de Responsabilidade Técnica – A.R.T. do responsável técnico pelas fases do projeto, execução, elaboração dos estudos ambientais e gestão do empreendimento (cópia)', null, 'art_fases', 'art_fases', null, 1);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (139, 'Plano de Controle Ambiental (PCA) do empreendimento, contendo as medidas mitigadoras e/ou compensatórias, com cronograma físico de execução', null, 'pca', 'pca', null, 1);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (140, 'Registro ou comprovante de solicitação emitido pela Agência Nacional de Telecomunicações – ANATEL (cópia)', null, 'reg_anatel', 'reg_anatel', null, 0);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (141, 'Memorial Descritivo das obras a serem executadas (altura, estrutura de fixação, local para equipamentos, ventilação)', null, 'memorial_desc_obras', 'memorial_desc_obras', null, 1);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (142, 'Documentação do imóvel', null, 'doc_imovel', 'doc_imovel', null, 0);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (143, 'Decreto de autorização, em se tratando de empresa ou sociedade estrangeira em funcionamento no País, e ato de registro ou autorização para funcionamento expedido pelo órgão competente, quando a atividade assim o exigir', null, 'decreto', 'decreto', null, 0);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (144, 'Apresentar mapa de localização da área do empreendimento em escala de 1:25.000 ou maior, contendo a área a ser licenciada, as coordenadas geográficas do local, distância desta até o curso de água mais próximo, articulação viária, rede de drenagem, benfeitorias em seu entorno imediato, uso e ocupação do solo', null, 'mapa_local', 'mapa_local', null, 1);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (145, 'Caracterização geral do empreendimento de acordo com TR ', null, 'caract_tr', 'caract_tr', null, 1);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (146, 'Projeto Executivo de Engenharia do empreendimento, de acordo com TR ', null, 'projeto_exec', 'projeto_exec', null, 1);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (147, 'Plano de Controle Ambiental (PCA), com as medidas mitigadoras e/ou compensatórias de acordo com TR ', null, 'pca_medidas', 'pca_medidas', null, 1);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (148, 'Alvará de funcionamento emitido pela Prefeitura Municipal', null, 'alvara_pm', 'alvara_pm', null, 0);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (149, 'Habite-se emitido pelo Corpo de Bombeiros', null, 'habitese', 'habitese', null, 0);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (150, 'Termo de compromisso firmado pela empresa registrante de agrotóxicos e afins, ou por sua entidade representativa, garantindo o recolhimento, transporte e destinação final das embalagens vazias recebidas, com previsão de multa diária, conforme legislação pertinente', null, 'termo_compromisso', 'termo_compromisso', null, 0);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (151, 'Programa de monitoramento de solo e da água (somente para de postos e centrais de recebimento)', null, 'prog_monitora', 'prog_monitora', null, 1);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (152, 'Apresentar  sistema de controle das quantidades e tipos de embalagens recolhidas e encaminhadas à destinação final, com as respectivas datas, em cumprimento ao artigo 55 do Decreto nº 4.074/2002', null, 'sist_controle', 'sist_controle', null, 1);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (153, 'Apresentar programa de monitoramento toxicológico dos funcionários, com exames médicos periódicos, com. verificação da existência de agrotóxicos no sangue, conforme Resolução CONAMA nº 334/2003', null, 'toxicologico', 'toxicologico', null, 1);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (154, 'Apresentar mapa de biossegurança, informando as áreas e as placas de sinalização de acordo com as normas técnicas vigentes', null, 'mapa_bio', 'mapa_bio', null, 1);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (155, 'Plano de Atendimento a Emergências (PAE) que deverá conter telefones de emergência, tais como do Corpo de Bombeiros; Centro de Informações Toxicológicas; hospital e/ou pronto socorro mais próximos; e do fabricante dos agrotóxicos comercializados, bem como materiais disponíveis para combate às emergências e equipes envolvidas nessas operações, e outras informações relevantes. Os referidos telefones deverão também estar expostos em local visível', null, 'pae', 'pae', null, 1);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (156, 'Apresentar cronograma de treinamento teórico e prático quanto às medidas preventivas e corretivas para o combate a acidentes com produtos agrotóxicos a todos os funcionários do empreendimento, conforme o Plano de Emergência apresentado encaminhando, posteriormente, cópia dos certificados dos mesmos, contendo o conteúdo programático, carga horária e qualificação do profissional ou da empresa ministrante do treinamento', null, 'cronograma', 'cronograma', null, 1);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (157, 'Apresentar ficha de Informações sobre Produtos Químicos (FISPQ) dos produtos comercializados (somente para comercialização de agrotóxicos)', null, 'fispq', 'fispq', null, 1);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (158, 'Apresentar programa de treinamento para a equipe que irá operar no recebimento, inspeção, triagem e armazenamento das embalagens (somente para postos e centrais de recebimento)', null, 'prog_treinamento', 'prog_treinamento', null, 1);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (159, 'Apresentar programa educativo visando à conscientização da comunidade do entorno sobre as operações de recebimento, armazenamento temporário e recolhimento para destinação final das embalagens vazias de agrotóxicos e afins devolvidas pelos usuários', null, 'prog_educativo', 'prog_educativo', null, 1);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (160, 'Apresentar relatório fotográfico do empreendimento, legendado e atualizado', null, 'rel_fotografico', 'rel_fotografico', null, 1);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (161, 'Em caso de utilização de água e coleta de esgoto da rede pública, apresentar documento emitido pela concessionária dos serviços de saneamento, e/ou Prefeituras Municipais, autorizando a ligação de distribuição de água e coleta de esgotos à rede oficial', null, 'doc_saneamento', 'doc_saneamento', null, 1);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (162, 'Em caso de utilização de águas subterrâneas ou superficiais, apresentar Outorga de Direito de Uso de Recursos Hídricos ou Dispensa de Outorga', null, 'outorga_dispensa', 'outorga_dispensa', null, 1);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (163, 'Responsável técnico pelo funcionamento dos postos e centrais de recebimento', null, 'rt_postos', 'rt_postos', null, 1);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (164, 'Cópia da Licença Ambiental anterior com comprovação de cumprimento das respectivas condicionantes', null, 'lic_ambiental_cond', 'lic_ambiental_cond', null, 1);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (165, 'Estudo Ambiental Simplificado – EAS, de acordo com o TR', 'TR-EASgeagro.pdf', 'eas', 'eas', null, 1);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (166, 'Cópia do ART com assinaturas reconhecidas do(s) elaborador(es) do CAR, EAS e CAD', null, 'art_car_eas_cad', 'art_car_eas_cad', null, 1);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (168, 'Documentos de Identificação do Titular/ Responsável Técnico/ Procurador (Cópia RG, CPF e Habilitação profissional)', null, 'doc_identificacao', 'doc_identificacao', null, 0);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (169, 'Cópia da documentação do imóvel Rural, de acordo com o disposto nas alíneas a e b do inciso VII do Art. 9º do Decreto Estadual nº 216 de 22/10/2011', null, 'doc_rural', 'doc_rural', null, 0);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (170, 'Cópia do comprovante de Imposto Territorial Rural – ITR do ano vigente', null, 'itr', 'itr', null, 0);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (171, 'Certificado de Cadastramento do Imóvel Rural - CCIR atualizado', null, 'ccir', 'ccir', null, 0);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (172, 'Cópia do Cadastro Nacional de Pessoa Jurídica – CNPJ', null, 'cnpj_copia', 'cnpj_copia', null, 0);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (173, 'Inscrição Estadual', null, 'ie', 'ie', null, 0);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (174, 'Documento de Constituição do empreendimento', null, 'doc_empreendimento', 'doc_empreendimento', null, 0);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (175, 'Cadastro Ambiental Declaratório-CAD ', 'cad_amb_declaratorio_ind_madeira.doc', 'cad', 'cad', null, 1);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (178, 'Cadastro Ambiental Declaratório-CAD-GECOS', 'cad_amb_declaratorio_gecos.docx', 'cad_gecos', 'cad_gecos', null, 1);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (179, 'Cadastro Ambiental Declaratório-CAD-GINFRA', 'cad_amb_declaratorio_ginfra.docx', 'cad_ginfra', 'cad_ginfra', null, 1);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (180, 'Caso o local do empreendimento esteja próximo de Unidade de Conservação Ambiental ou em área de amortecimento delimitada pelo Plano de Manejo da Unidade, apresentar documento de anuência do órgão ambiental estadual ou federal', null, 'plano_manejo', 'plano_manejo', null, 1);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (181, 'Inventário Florestal da(s) área(s) a ser (em) desmatada(s), se for o caso, para fins de obtenção da Autorização de Supressão Vegetal – ASV, de competência desta SEMA', null, 'inventario_flor', 'inventario_flor', null, 1);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (182, 'Caso o empreendimento utilize explosivo, apresentar licença do Ministério do Exército', null, 'licenca_me', 'licenca_me', null, 1);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (183, 'Caso seja necessário utilizar produtos químicos, apresentar autorização do órgão responsável para uso, transporte e armazenamento de produtos químicos', null, 'autoriz_prodquimico', 'autoriz_prodquimico', null, 1);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (184, 'Anotações de Responsabilidade Técnica – ART’S dos responsáveis pela elaboração e execução do(s) projetos executivo(s) e pela elaboração do RCA (cópias autenticadas e atualizadas)', null, 'art_rca', 'art_rca', null, 1);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (186, 'Cadastro Ambiental Declaratório-CAD-GEMINA/GEMIM', 'cad_amb_declaratorio_gmina.docx', 'cad_gemina', 'cad_gemina', null, 1);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (187, 'Cadastro Ambiental Declaratório-CAD-GIND', 'cad_amb_declaratorio_gind.docx', 'cad_gind', 'cad_gind', null, 1);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (188, 'Cadastro Ambiental Declaratório-CAD-GEICOS', 'cad_amb_declaratorio_geicos.docx', 'cad_geicos', 'cad_geicos', null, 1);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (189, 'Cadastro Ambiental Declaratório-CAD  (REFLORESTAMENTO)', 'cad_amb_declaratorio_reflorestamento.docx', 'cad_reflor', 'cad_reflor', null, 1);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (190, 'Caso seja detectada a existência de sitio arqueológico ou espeleológico, apresentar projeto de resgate ou medidas mitigadoras para proteção, devidamente autorizadas ou aprovadas pelo IPHAN', null, 'iphan', 'iphan', null, 1);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (191, 'Caso a área do empreendimento esteja próxima a área indígena ou de interesse da FUNAI (raio de até 10 km), apresentar documento de anuência da FUNAI', null, 'funai', 'funai', null, 1);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (192, 'Cadastro Ambiental Declaratório-CAD  (AGROPASTORIL)', 'cad_amb_declaratorio_agropastoril.docx', 'cad_agropastoril', 'cad_agropastoril', null, 1);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (193, 'Elaboração do Estudo Ambiental Simplificado - EAS', 'Termo_de_Referencia_Industria_Simplificado.odt', 'cad_gind_termo', 'cad_gind_termo', null, 1);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (194, 'Cadastro Ambiental Simplificado - CAS', 'cad_amb_simplificacao_infraestrutura_equipamento_comunitario.doc', 'cad_cas', 'cad_cas', null, 1);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (195, 'Documento da Licença de Operação / Renovação da Licença de Operação Vigente', null, 'lorlo', 'lorlo', null, null);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (196, 'Documento de Evidências de atendimento às condições da licença vigente', null, 'evidencias', 'evidencias', null, null);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (561, 'RLAU - Renovação de Licença Ambiental Unica', null, 'RLAU', 'RLAU', 'DOC_RLAU', null);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (562, 'ALP - Atualizaço de Licença Prévia', null, 'ALP', 'ALP', 'DOC_ALP', null);
INSERT INTO licenciamento.tipo_documento (id, nome, caminho_modelo, caminho_pasta, prefixo_nome_arquivo, codigo, tipo_analise) VALUES (563, 'CA - Cadastro de Aquicultura', null, 'CA', 'CA', 'DOC_CA', null);

ALTER TABLE licenciamento.tipo_documento DROP COLUMN ativo;
ALTER TABLE licenciamento.tipo_documento DROP COLUMN data_cadastro;
ALTER TABLE licenciamento.tipo_documento DROP COLUMN id_usuario_licenciamento;
