package security;


public enum Acao {

	LISTAR_CARACTERIZACAO("LIA_LISTAR_CARACTERIZACAO"),
	CADASTRAR_CARACTERIZACAO("LIA_CADASTRAR_CARACTERIZACAO"),

	LISTAR_EMPREENDIMENTO("LIA_LISTAR_EMPREENDIMENTO"),
	CADASTRAR_EMPREENDIMENTO("LIA_CADASTRAR_EMPREENDIMENTO"),
	ALTERAR_EMPREENDIMENTO("LIA_ALTERAR_EMPREENDIMENTO"),
	EXCLUIR_EMPREENDIMENTO("LIA_EXCLUIR_EMPREENDIMENTO");

	public String codigo;

	private Acao(String codigo) {

		this.codigo = codigo;
	}

}