package models.caracterizacao;

public enum TipoPergunta {
	
	SIM_NAO,
	VALIDA_APP,
	VALIDA_MZEE,
	VALIDA_PASSIVO,
	VALIDA_AREA_CONSOLIDADA,
	VALIDA_ZONA_CONSOLIDACAO,
	VALIDA_RESERVA_LEGAL,
	VALIDA_SISTEMA_ELETRICO,
	VALIDA_CONSTRUCAO,
	VALIDA_LOTES,
	VALIDA_PONTES

}
